### ISSUE TITLE
MP Config - introduce constant for empty string

### ISSUE THREAD

**Issue by manovotn** [eclipse/microprofile-context-propagation#160] opened 2019-05-14 09:21 UTC
Currently we allow users to set their defaults via MP config in the following way - `ThreadContext/propagated=`.
This is interpreted as "no contexts are to be propagated".

Now, looking at the changes proposed in https://github.com/eclipse/microprofile-config/issues/397 and the respective PR https://github.com/eclipse/microprofile-config/pull/407, we are going to have to change this.
With the above, empty value means you won't be able to see the key is there at all.

Hence I would suggest some constant, much like we have the `REMAINING` one, but this one would have to be something like `none`?

What do you guys think?

**Comment by manovotn** [comment] 2019-05-14 09:26
Note that the above MP config change will be a breaking change in the next major version but that doesn't matter we cant get ahead and design something that we won't need to change later.

**Comment by njr-11** [comment] 2019-05-14 14:39
@manovotn thanks for catching this.  I added some comments to that pull questioning a few things and pointing out that it doesn't actually resolve the issue I opened with MP Config and actually makes it worse for us.  I'll watch for a reply and see where this goes.  We will definitely want to update MP Context Propagation per whatever outcome is decided upon.

**Comment by njr-11** [comment] 2019-05-14 16:25
In the replies to my questions under eclipse/microprofile-config#407, they have confirmed that with their new design, the empty value will result in a size 0 array.  Oddly enough, there appears to be an implementation of MP Config (not the one I've been using) where the absence of a configured _key_   is being treated the same as a key/value pair where the key is specified and the value is empty.  In that case, implementations will be able to work around this by either supplying the defaults up front as a config source, or by utilizing a new interface called ConfigAccessor, which allows a default to be supplied at the time of invocation.

**Comment by manovotn** [comment] 2019-05-14 19:41
> In the replies to my questions under eclipse/microprofile-config#407, they have confirmed that with their new design, the empty value will result in a size 0 array

Hmm, then I will have to re-read that. My understanding was that empty value is basically ignored value.
And from the first look at those comments, it still seems to be the case. David's case is basically an upfront default but that doesn't fit us. For out *current* design, empty values != default value.
We either need to be able to get into spec that *missing* value equals empty array (if array is output type) or we need to declare a string meaning just that like I suggested (which I think is probably the path of least resistance).

**Comment by manovotn** [comment] 2019-05-16 14:17
@njr-11 this comment and the answer to it might interest you https://github.com/smallrye/smallrye-config/issues/83#issuecomment-493078187

The first option with purely optional doesn't work for us as it doesn't tell us whether the key exists.
The second option via accessor should work as we desire if I understand it correctly.
That being said, I am still unsure what happens if you use that to get a value that actually isn't defined by user at all - do you get what you put in `orElse()` or what you set into `withDefault()`?

**Comment by dmlloyd** [comment] 2019-05-16 14:47
> That being said, I am still unsure what happens if you use that to get a value that actually isn't defined by user at all - do you get what you put in `orElse()` or what you set into `withDefault()`?

You get what was sent in for `withDefault()`; picture it like an ad-hoc lowest-priority config source for just that one value.

**Comment by njr-11** [comment] 2019-05-16 15:13
The following is the example copied from https://github.com/smallrye/smallrye-config/issues/83#issuecomment-493078187 which is being discussed above,
```
String[] array = config.access("my.key", String[].class).withStringDefault("foo,bar").getOptionalValue().orElse(EMPTY_ARRAY);
```

While I appreciate that this pattern will provide a solution for us, I should point out that it seems counterintuitive.  From reading the JavaDoc, I would never have interpreted it that way.

Here is how I would have expected it to work: if `orElse` is needed to supply EMPTY_ARRAY to the `Optional`, that means the empty value is treated as though it does not exist in config.  But this is the same purpose that `withDefault` has (for when a value does not exist in config).  So I would logically conclude that one or the other of `orElse` and `withDefault` is redundant and will never be invoked.  It really makes no sense to me how in one case (value not present) the `withDefault` value is used and in the semantically identical case (empty value treated as not present) the `orElse` value is used.

It seems to me the only way for this to make sense would be if empty value were simply treated as a size 0 (empty) array, in which case the `orElse` shouldn't be needed at all because there _is_ a value.

**Comment by dmlloyd** [comment] 2019-05-16 16:27
> The following is the example copied from [smallrye/smallrye-config#83 (comment)](https://github.com/smallrye/smallrye-config/issues/83#issuecomment-493078187) which is being discussed above,
> 
> ```
> String[] array = config.access("my.key", String[].class).withStringDefault("foo,bar").getOptionalValue().orElse(EMPTY_ARRAY);
> ```
> 
> While I appreciate that this pattern will provide a solution for us, I should point out that it seems counterintuitive. From reading the JavaDoc, I would never have interpreted it that way.

The JavaDoc is not up to date with the current proposal.

> Here is how I would have expected it to work: if `orElse` is needed to supply EMPTY_ARRAY to the `Optional`, that means the empty value is treated as though it does not exist in config. But this is the same purpose that `withDefault` has (for when a value does not exist in config). So I would logically conclude that one or the other of `orElse` and `withDefault` is redundant and will never be invoked. It really makes no sense to me how in one case (value not present) the `withDefault` value is used and in the semantically identical case (empty value treated as not present) the `orElse` value is used.
> 
> It seems to me the only way for this to make sense would be if empty value were simply treated as a size 0 (empty) array, in which case the `orElse` shouldn't be needed at all because there _is_ a value.

Doing so however puts us back into many of the problem scenarios outlined by the tables shown in eclipse/microprofile-config#407.  What is an empty value really?  Can you have an array with one empty value, and what does that mean?  What's the difference between an empty and missing value?  How do you force a value to be considered "missing" if it is distinct from empty?

**Comment by njr-11** [comment] 2019-06-10 14:03
Given that eclipse/microprofile-config#407 was not merged in time for [MicroProfile 3.0](https://projects.eclipse.org/projects/technology.microprofile/releases/microprofile-3.0), it looks like the window for breaking changes in MP Config has been missed and therefore MP Context Propagation does not yet need to cope with its possible implications.  For this reason, I am recommending that we defer this issue to future and revisit if/when necessary.  The safest thing for us to do in the face of the uncertainty in this area is to initially not introduce any new constant at all, which will give us the widest range of available options for reacting to whatever happens in MicroProfile config if/when changes are made there.

**Comment by manovotn** [comment] 2019-06-13 12:19
Given the current status, I would also lean towards deferring this issue for the time being.

**Comment by njr-11** [comment] 2020-09-22 20:55
I just received a notification that issue https://github.com/eclipse/microprofile-config/issues/397 which I opened against MP Config to fully standardize the way of configuring an empty list/array has been 'resolved' by issue https://github.com/eclipse/microprofile-config/pull/598

My understanding of https://github.com/eclipse/microprofile-config/pull/598 is that it now bans empty list/array as values in MP Config.  Refer to the table that now appears here:
https://github.com/eclipse/microprofile-config/blob/master/spec/src/main/asciidoc/configexamples.asciidoc

Given this, we will be forced to make changes to MP Context Propagation to invent our own mechanism for reinterpreting a non-empty value to mean empty list.  The old way won't work anymore and MP Config doesn't provide any new way, leaving us no choice here.  The value of `None` that @manovotn suggests in the issue description seems appropriate for this.  The [mpconfig asciidoc page](https://github.com/eclipse/microprofile-context-propagation/blob/master/spec/src/main/asciidoc/mpconfig.asciidoc) will also need an update, somehow explaining that if you are MP Config 2.0? or later then use the new way to specify empty lists, but if using an earlier MP Config, then specify empty lists in the original way.

**Comment by njr-11** [comment] 2020-09-25 22:01
It turns out we already had a constant for ThreadContext.NONE, which was there as a convenience for code that wanted to be explicit when using the builder.  Under #198 I extended the usage of this value to apply to mpconfig as well, updated asciidocs and the tck accordingly, and tested it against OpenLiberty's MP Context Propagation impl (it needed a one line change to reinterpret the "None" value as an empty array) after which the updated TCK passes.
@manovotn could you review #198 ?

**Comment by Emily-Jiang** [comment] 2020-09-26 22:27
You could still use empty string and then check getPropertyName to ensure the property was defined. In this case, you can do getOptionalValue and put the empty as the default.

**Comment by njr-11** [comment] 2020-09-28 14:37
> You could still use empty string and then check getPropertyName to ensure the property was defined. In this case, you can do getOptionalValue and put the empty as the default.

I think you are referring to the `getPropertyNames` method on `Config`, for which the JavaDoc states that it _might_ let you iterate over all configured property names, but it isn't required to.  The JavaDoc explicitly states that `it is allowed for this method to return an empty set always`.  So this suggestion isn't a reliable approach that can be guaranteed to work on all implementations.

Furthermore, even if there were some way to workaround or sidestep this behavior change, it just seems wrong for another spec such as ours to think that it can take away MP Config's new standard way of overriding config properties to be considered "unspecified" and repurpose it to indicate a configured value -- even if that was what it used to mean for us.  Our own dislike of it being accomplished via a behavior change doesn't make it right for us to override the authority of MP Config and suppress it in our spec.  Given that you've now introduced non-configured property as the standard meaning, that's what everyone ought to be able to consistently rely upon going forward.

**Closed** 2020-10-07 13:50 UTC
